### ISSUE TITLE
Plug-in naming

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cobol-language-support-intellij#7]
The name of the Zowe™ COBOL Language Support plug-in should be updated to conform to the Linux Foundation's trademark usage policy (https://www.linuxfoundation.org/legal/trademark-usage). Specifically, the section `Rules and Policies Applicable to Marks Owned by The Linux Foundation`, includes a list of acceptable name formats.

If I had to choose a name, I would suggest something like "COBOL Language Support for Zowe™".

**Comment by adam-wolfe** [comment]
According to the TSC discussion on July 18, 2024, concerns around LF trademark usage may not apply for the Zowe COBOL Language Support plug-in because it is produced as part of the Zowe project.

@jmertic - Is this correct?

**Comment by jmertic** [comment]
That is correct @adam-wolfe - if the COBOL language support is provided by the Zowe project, then no, it does not need to comply with the trademark policy.  The policy is for how OTHERS use the Zowe trademark.
